### ISSUE TITLE
Team View

### ISSUE THREAD

**Issue by Dainc007** [Dainc007/menagoleague.pl#19]
W fifach zakladka Team wyglada mniej wiecej niezmiennie tak:
![teamtab](https://user-images.githubusercontent.com/62115633/127661187-605e18df-d368-4ff9-aefa-18ca75f166e3.png)

My na razie pójdziemy trochę na łatwiznę i będzie nas interesować tylko ta jedna sekcja:
![teamtab](https://user-images.githubusercontent.com/62115633/127661410-9fb5a025-d119-40fa-abb5-1620317a4d70.png)
Z tymże w niej też pójdziemy na łatwiznę i nie będziemy się w niej bawić w formacje, a wrzucimy tam info o drużynie w takiej formie:
![teamstatus](https://user-images.githubusercontent.com/62115633/127661564-886bb866-b701-46a3-86d4-c9737bb0edc3.png)
![teamatrybuty](https://user-images.githubusercontent.com/62115633/127661579-8cbfc99b-f617-44ba-8440-9669317c9589.png)

Czyli wywalimy wszystkich piłkarzy ze scrollbarem i wszystkie atrybuty :)
1. Nie wiem, czy damy zdjęcie twarzy piłkarza.
2. NA PEWNO NIE BĘDZIE CAŁEJ SYLWETKI PIŁKARZA PO NAJECHANIU 👯 
Cała prawa strona nas na razie nie interesuje:
![teamatrybuty](https://user-images.githubusercontent.com/62115633/127662015-357cde78-9f9c-4d6f-a078-df0bd206eeb8.png)

"prawą" część zostawiamy na razie pustą, niezagospodarowaną.

Musimy też dodać buttona, najlepiej obok "Rola" dać jakiś przycisk, który nam pokaże dostępne akcje z piłkarzem:
![teambuttony](https://user-images.githubusercontent.com/62115633/127662430-29e45fa9-82e7-4a7f-9826-b61b8fad8718.png)

HINT: u nas tych akcji będzie co najmniej dwa razy tyle

**Comment by Dainc007** [comment]
Jeszcze jedna korekta, liste zawodnikow podzielić na dwie czesci: Główna (podstawowa 11) i Podrzedna (rezerwowi). U rezerwowych dodatkowy button przenieś do wyjsciowego skladu, a w glownej "posadź na ławce
![team](https://user-images.githubusercontent.com/62115633/127669522-6bd2cf69-6093-4511-98c1-24b2155cb90c.png)
"

**Comment by Fronikuniu** [comment]
Initial version of squad is done and need add required backend.

**Comment by Dainc007** [comment]
done
