### ISSUE TITLE
view for knockout stage and champions league

### ISSUE THREAD

**Issue by Dainc007** [Dainc007/menagoleague.pl#52]
![Zrzut ekranu 2021-09-19 o 19 59 12](https://user-images.githubusercontent.com/62115633/133938358-3172ea72-7ce4-4c6c-8fae-80ed9fea937b.png)
![Zrzut ekranu 2021-09-19 o 19 57 24](https://user-images.githubusercontent.com/62115633/133938361-cb8d58a0-17e3-48e9-ab76-b5d10a847c11.png)

**Comment by Fronikuniu** [comment]
Done
![image](https://user-images.githubusercontent.com/26391807/135711388-7a5ad652-dc59-47b6-9631-39487317bb15.png)
![image](https://user-images.githubusercontent.com/26391807/135711394-6ec492a1-32af-48a5-96fa-9dade3a170f2.png)
