### ISSUE TITLE
Central View

### ISSUE THREAD

**Issue by Dainc007** [Dainc007/menagoleague.pl#6]
Site for logged users is has to be as much similar to Fifa games panel as it's possible. You can see how it looks like now if you go on www.menagoleague.pl and log on user 'admin' password 'admin'.

 *In future, it would be friendly for users to add Two basic color options. One, for younger users with bright colors and second one, less colorful.

**Comment by Fronikuniu** [comment]
Now finished, you have to change the condition for the Game menu to be displayed and add a backend

**Comment by Dainc007** [comment]
Może dojść do sytuacji, w której danego dnia gracz będzie miał dwa mecze do rozegrania.
Trzeba wykombinować, jak to najlepiej rozwiązać, żeby nic się nie rozjechało.
![Zrzut ekranu 2021-08-7 o 15 40 05](https://user-images.githubusercontent.com/62115633/128602160-4e01666b-a7ba-4f59-a615-298d13ffba46.png)

**Comment by Dainc007** [comment]
W wolnej chwili, chciałbym zobaczyć jak to wygląda gdybyśmy nieco pomniejszyli elementy i sprobowali zmieścić cztery rzędy.
![Zrzut ekranu 2021-08-7 o 15 42 20](https://user-images.githubusercontent.com/62115633/128602203-b0940614-d7a5-4980-bada-c80ed347b4e5.png)

**Comment by Dainc007** [comment]
drobny bug
![Zrzut ekranu 2021-08-7 o 16 48 56](https://user-images.githubusercontent.com/62115633/128604147-95542690-cc9f-4915-87b3-a101cba004ce.png)

**Comment by Dainc007** [comment]
![Zrzut ekranu 2021-08-7 o 16 55 07](https://user-images.githubusercontent.com/62115633/128604320-517df9a7-c639-494d-ab8b-78ceab8400fa.png)
tutaj chyba CSSa do ikonek tez brakuje, chyba ze to przez ich rozmiar

**Comment by Dainc007** [comment]
normalnie mecz był w Piątek, ale na mobilce coś się rozjeżdza i ikonka z piątku preznosi się do soboty.
![Zrzut ekranu 2021-08-7 o 17 57 58](https://user-images.githubusercontent.com/62115633/128606177-18442169-c38b-4a2c-a7cf-a9660d713325.png)
![Zrzut ekranu 2021-08-7 o 17 57 39](https://user-images.githubusercontent.com/62115633/128606179-9708bef6-14ab-4967-8a10-403363df8253.png)
